"""Gmail SMTP email digest notifier."""

import logging
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from agent.config import (
    GMAIL_APP_PASSWORD,
    GMAIL_RECIPIENT,
    GMAIL_SMTP_HOST,
    GMAIL_SMTP_PORT,
    GMAIL_USER,
)

logger = logging.getLogger(__name__)


def _build_html_digest(papers: list[dict]) -> str:
    """Build an HTML email body from the list of curated papers."""
    today = datetime.now().strftime("%B %d, %Y")

    # Group papers by category
    by_category: dict[str, list[dict]] = {}
    for p in papers:
        cat = p.get("category", "other")
        by_category.setdefault(cat, []).append(p)

    sections = ""
    for category, cat_papers in sorted(by_category.items()):
        items = ""
        for p in cat_papers:
            score = p.get("score", "?")
            summary = p.get("summary", "No summary available.")
            url = p.get("url", "#")
            local_path = p.get("local_path", "")

            local_info = ""
            if local_path:
                local_info = f'<br><small>Local: <code>{local_path}</code></small>'

            items += f"""
            <div style="margin-bottom: 16px; padding: 12px; border-left: 3px solid #4A90D9; background: #f8f9fa;">
                <strong><a href="{url}" style="color: #1a73e8; text-decoration: none;">{p['title']}</a></strong>
                <span style="color: #666; font-size: 12px;">[Score: {score}/10]</span>
                <br><span style="color: #333; font-size: 14px;">{summary}</span>
                {local_info}
            </div>
            """
        sections += f"""
        <h2 style="color: #333; border-bottom: 1px solid #ddd; padding-bottom: 4px;">
            {category.upper()}
        </h2>
        {items}
        """

    return f"""
    <html>
    <body style="font-family: -apple-system, Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #1a73e8;">AI Paper Digest - {today}</h1>
        <p style="color: #666;">{len(papers)} curated papers found today.</p>
        {sections}
        <hr style="border: none; border-top: 1px solid #ddd;">
        <p style="color: #999; font-size: 12px;">Generated by AI Paper Agent (Qwen)</p>
    </body>
    </html>
    """


def send_email_digest(papers: list[dict]) -> bool:
    """Send the daily paper digest via Gmail SMTP."""
    if not GMAIL_USER or not GMAIL_APP_PASSWORD:
        logger.error("Gmail credentials not configured in .env file")
        return False

    if not papers:
        logger.info("No papers to send — skipping email")
        return True

    today = datetime.now().strftime("%Y-%m-%d")
    recipient = GMAIL_RECIPIENT or GMAIL_USER

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"AI Paper Digest - {today} ({len(papers)} papers)"
    msg["From"] = GMAIL_USER
    msg["To"] = recipient

    html_body = _build_html_digest(papers)
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(GMAIL_SMTP_HOST, GMAIL_SMTP_PORT) as server:
            server.starttls()
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.send_message(msg)
        logger.info(f"Email digest sent to {recipient} with {len(papers)} papers")
        return True
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False
